### ISSUE TITLE
Password field visible after authentication then page refresh

### ISSUE THREAD

**Issue by MetaBureau** [lupas/nuxt-firebase-demo#16] opened 2020-03-05 01:49 UTC
I have cloned, generated and deployed to Firebase as per the following config  
```
      onFirebaseHosting: true,
      services: {
        auth: {
          initialize: {
            onSuccessAction: 'handleSuccessfulAuthentication',
            ssr: true
          }
        },
```
The password field is visible on page refresh, but the user is considered authenticated.

**Comment by lupas** [comment] 2020-03-05 16:36
@MetaBureau 
Can you check under **Google Chrome -> Dev Tools -> Application -> Service Workers** if the firebase-auth-sw.js is green and running?

**Comment by MetaBureau** [comment] 2020-03-05 23:14
It is.
https://stins-nuxt-auth.firebaseapp.com/

**Comment by MetaBureau** [comment] 2020-03-06 01:59
I have deployed to Heroku and do not experience the same issue:
https://nuxtfiretest.herokuapp.com/

**Comment by lupas** [comment] 2020-03-06 08:30
Interesting, with shift+reload I can see it now too:
<img width="1440" alt="Screenshot 2020-03-06 at 09 26 11" src="https://user-images.githubusercontent.com/4020037/76065789-93ec0480-5f8c-11ea-8b7a-f579fa8a4dbd.png">

With a hard reload (and user was previously logged in):

- First the user is not logged in (login fields are visible)
- Some seconds later user is logged in
- Email Field disappeared, but password field and login buttons are still visible

After a regular refresh all is good again. Same applies to the official Demo, and doesn't seem to matter where it is hosted.

I'll have a look at it.

**Comment by dominioraiz** [comment] 2020-05-07 22:35
Hi @lupas , first, thanks for this excellent module! 🙂

I'm experiencing exactly what was mentioned above about hard reload

In my case, until the user verification, what is in `div(v-if="!isLoggedIn")` is shown 

After a few seconds, it finally shows the element to the logged in user

I checked the console and it also displays this warning:

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

Any ideas on how to load the component only after the store?

**Comment by lupas** [comment] 2020-11-10 21:49
Closing this because of its age and because since the last comment was before the major version upgrade to nuxtjs/firebase v7.

If you still run into this issue please open an issue on the [official module repository](https://github.com/nuxt-community/firebase-module).

**Closed by lupas** 2020-11-10 21:49 UTC

**Comment by jillztom** [comment] 2021-01-06 03:25
Wondering if there is any update on this issue? I'm facing a similar issue. The home page (index.vue) when refreshing (which has a navigation menu where I check for `isLoggedIn`) is erring out the Vue Warn mentioned above. This means the user is not authenticated at server side and only authenticated at client side-thus resulting different HTML in server and client. But if I go to another page with a middleware `authenticated` with the same navigation bar, the user is logged in at server side on refresh and no warnings. However, the page is blank for a few millisecond and everything is rendered.
